---

- hosts: all
  name : Install assessment tools
  become: no
  become_method: sudo
  vars:
    vm_tools_source_dir: "{{ [vm_tools_dir, 'src'] | path_join }}"
    vm_hostname: "kali-ops"
    vm_username: "kali"
    repositories:
      # Git Only
      - name: "AggressorScripts"
        repo: "github.com/bluscreenofjeff/AggressorScripts"

      - name: "AggressorAssessor"
        repo: "github.com/FortyNorthSecurity/AggressorAssessor"

      - name: "PowerUpSQL"
        repo: "github.com/NetSPI/PowerUpSQL"

      - name: "discover"
        repo: "github.com/leebaird/discover"

      - name: "Sublist3r"
        repo: "github.com/aboul3la/Sublist3r"

      - name: "BloodHound"
        repo: "github.com/BloodHoundAD/BloodHound" # Download the release instead

      - name: "Seclists"
        repo: "github.com/danielmiessler/SecLists"

      - name: "Nlzr"
        repo: "github.com/noahpowers/nlzr"

      - name: "Gnmap Parser"
        repo: "github.com/m1j09830/gnmap-parser.git"

      - name: "SIET"
        repo: "github.com/frostbits-security/SIET.git"

      - name: "cisot7"
        repo: "github.com/theevilbit/ciscot7.git"

      # Python3 tools
      - name: "PKINITtools"
        repo: "github.com/dirkjanm/PKINITtools"
        pip: yes # Run pip install
        pip_requirements_file: "requirements.txt"

      - name: "impacket"
        repo: "github.com/ThePorgs/impacket"
        pipx: yes # Run pip install

      - name: "krbrelayx"
        repo: "github.com/dirkjanm/krbrelayx"
        pip: yes # Run pip install
        pip_dependencies:
          - "impacket"
          - "dsinternals" # cannot be installed with pipx

      - name: "mitm6"
        repo: "github.com/dirkjanm/mitm6"
        pipx: yes # Run pip install

      - name: "pre2k"
        repo: "github.com/garrettfoster13/pre2k"
        pipx: yes # Run pip install

      - name: "CrackMapExec"
        repo: "github.com/Porchetta-Industries/CrackMapExec"
        pipx: yes # Run pip install
        package_dependencies:
          - "libssl-dev"
          - "libffi-dev"
          - "python-dev-is-python3"
          - "build-essential"

      - name: "PetitPotam"
        repo: "github.com/topotam/PetitPotam"
        pip: yes # Run pip install
        pip_dependencies:
          - "impacket"

      - name: "Responder"
        repo: "github.com/lgandx/Responder"
        pip: yes # Run pip install
        pip_requirements_file: "requirements.txt"

      - name: bloodhound-py
        repo: "github.com/fox-it/BloodHound.py"
        pipx: yes # Run pip install

      - name: "SeeYouCM-Thief"
        repo: "github.com/trustedsec/SeeYouCM-Thief"
        pip: yes
        pip_requirements_file: "requirements.txt"

      - name: "Certipy"
        repo: "github.com/ly4k/Certipy"
        pipx: yes

      - name: "spraycharles"
        repo: "github.com/Tw1sm/spraycharles"
        pipx: yes

      - name: "RITM"
        repo: "github.com/Tw1sm/RITM"
        pipx: yes

      - name: "DonPAPI"
        repo: "github.com/login-securite/DonPAPI.git"
        pipx: yes

      - name: "Assessment-Toolkit"
        repo: "github.com/m1j09830/Assessment-Toolkit.git"
        pipx: yes

      - name: "pywhisker"
        repo: "github.com/ShutdownRepo/pywhisker.git"
        pip: yes
        pip_requirements_file: "requirements.txt"

      - name: "Auto-Egress-Assess"
        repo: "github.com/tarrell13/Auto-Egress-Assess.git"
        pip: yes
        pip_requirements_file: "requirements.txt"

      - name: "NetExec"
        repo: "github.com/Pennyw0rth/NetExec.git"
        pipx: yes
        package_dependencies:
          - "libssl-dev"
          - "libffi-dev"
          - "python-dev-is-python3"
          - "build-essential"

    packages: # Apt packages
      - nmap
      - 7zip
      - zip
      - unzip
      - tar
      - flameshot
      - neo4j # Maybe make this a service?
      - docker.io

    # Todo: Define "creates" for these to solve idempotency
    go_repos: # go tools
      - "github.com/lkarlslund/ldapnomnom@latest"
      - "github.com/projectdiscovery/pdtm/cmd/pdtm@latest"
      - "github.com/tomnomnom/waybackurls@latest"
      - "github.com/projectdiscovery/pdtm/cmd/pdtm@latest"

  tasks:

    - name: Update hosts file
      become: yes
      lineinfile:
        dest: /etc/hosts
        line: '127.0.1.1  {{ vm_hostname }}'

    - name: Update hostname
      become: yes
      hostname:
        name: "{{ vm_hostname }}"

    # Baseline tasks
    - name: Update APT Repo
      become: yes
      apt:
        update_cache: yes

    - name: Install Python 3 packages
      become: yes
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - include_tasks: ./apt.yml
      loop: "{{ packages }}"

    - include_tasks: ./vscode.yml

    - include_tasks: ./golang.yml

    - name: Update PATH
      become: yes
      lineinfile:
        dest: /etc/zsh/zshrc
        line: 'export PATH=$PATH:/usr/local/go/bin:/home/{{ vm_username }}/.local/bin:$HOME/go/bin'

    # - name: Add Go Bin to PATH
    #   become: yes
    #   copy:
    #     dest: /etc/profile.d/golang-path.sh
    #     content: 'export PATH=$PATH:/usr/local/go/bin'
    #     owner: '{{ vm_username }}'
    #     group: '{{ vm_username }}'
    #     mode: 'u=rw,go=r'

    - include_tasks: ./gotools.yml
      loop: "{{ go_repos }}"

    # Tools directory setup
    - name: Create Tools Directory
      become: yes
      file:
        path: "{{ vm_tools_dir }}"
        owner: "{{ vm_username }}"
        group: "{{ vm_username }}"
        state: directory
        mode: 0755

    - name: Create Tools Source Directory
      become: yes
      file:
        path: "{{ vm_tools_source_dir }}"
        owner: "{{ vm_username }}"
        group: "{{ vm_username }}"
        state: directory
        mode: 0755

    - name: Create User Local Bin Directory
      file:
        path: "/home/{{ vm_username }}/.local/bin"
        owner: "{{ vm_username }}"
        group: "{{ vm_username }}"
        state: directory
        mode: 0755

    - name: Create Bash Log Directory
      become: yes
      file:
        path: "/opt/op-log"
        owner: "{{ vm_username }}"
        group: "{{ vm_username }}"
        state: directory
        mode: 0755

    - name: Add User Local Bin to PATH
      become: yes
      copy:
        dest: /etc/profile.d/golang-path.sh
        content: 'export PATH=$PATH:/usr/local/go/bin'
        owner: '{{ vm_username }}'
        group: '{{ vm_username }}'
        mode: 'u=rw,go=r'

    # Clone repositories and link to tools directory
    - include_tasks: git-clone.yml
      loop: "{{ repositories }}"

    - name: Link Tool Repos to Tool Directory
      file:
        src: "{{ vm_tools_source_dir }}/{{ item.repo }}"
        dest: "{{ vm_tools_dir }}/{{ item.name }}"
        state: link
      with_items: "{{ repositories }}"

    - name: Pip Install PipX
      ansible.builtin.pip:
        name: pipx
        state: present
      register: pipx_install

    - name: Ensure pipx Path
      ansible.builtin.shell:
        cmd: "python3 -m pipx ensurepath"
      when: pipx_install is defined

    - include_tasks: pip-install.yml
      loop: "{{ repositories }}"

    - include_tasks: pipx-install.yml
      loop: "{{ repositories }}"

    # BloodHound GUI
    # TODO: Break this out into it's own role
    # TODO: Install neo4j
    - include_tasks: bloodhound.yml

    # BurpSuite Pro
    # TODO: Break this out into it's own role
    - include_tasks: burpsuite-pro.yml

    - name: Set ZSH for User
      become: yes
      ansible.builtin.user:
        name: "{{ vm_username }}"
        shell: "/bin/zsh"

    # Enable Kali Logging
    - name: Enable Kali Logging
      shell: |
        sudo mkdir -p /opt/op-log
        sudo chown -R ${vm_username}:${vm_username} /opt/op-log

        # This base64 blob decodes as follows:
        echo test "$(ps -ocommand= -p $PPID | awk '{print $1}')" == 'script' || (script -f /opt/op-log/$(date +"%Y-%m-%d_%H-%M-%S")_shell.log)
        # export PS1="[\$(date +\"%Y-%m-%d %H:%M:%S\")]"$'\n'"$PS1"
        # set -o vi

        echo "bWtkaXIgLXAgL29wdC9vcC1sb2cKdGVzdCAiJChwcyAtb2NvbW1hbmQ9IC1wICRQUElEIHwgYXdrICd7cHJpbnQgJDF9JykiID09ICdzY3JpcHQnIHx8IChzY3JpcHQgLWYgL29wdC9vcC1sb2cvJChkYXRlICsiJVktJW0tJWRfJUgtJU0tJVMiKV9zaGVsbC5sb2cpCmV4cG9ydCBQUzE9IltcJChkYXRlICtcIiVZLSVtLSVkICVIOiVNOiVTXCIpXSIkJ1xuJyIkUFMxIgpzZXQgLW8gdmkK" |base64 -d >>  ~/.zshrc

        echo "termcapinfo xterm* ti@:te@" >> ~/.screenrc
      args:
        creates: "/opt/op-log/"

    # Gowitness Install
    - include_tasks: gowitness.yml

    - include_tasks: sublime.yml

    - include_tasks: nessus.yml

    - include_tasks: docker.yml
