- name: Install Docker Compose Plugin
  become: yes
  ansible.builtin.shell: |
    DOCKER_CONFIG=/usr/local/lib/docker
    mkdir -p $DOCKER_CONFIG/cli-plugins
    curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
    chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
  args:
    creates: /usr/local/lib/docker/cli-plugins/docker-compose

- name: Allow {{ vm_username }} user to run Docker
  become: yes
  ansible.builtin.user:
    name: "{{ vm_username }}"
    append: yes
    groups: docker
