- name: Fetch Nessus version number
  shell: |
    curl -sS 'https://www.tenable.com/downloads/nessus?loginAttempted=true' | grep -oP '(Nessus - (\d+\.){2}\d+)<' | cut -f 3 -d ' ' | cut -f 1 -d '<'
  register: nessus_version_raw

- name: Extract version number
  set_fact:
    nessus_version: "{{ nessus_version_raw.stdout }}"

- name: "Download Nessus {{ nessus_version }}"
  ansible.builtin.get_url:
    url: https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-{{ nessus_version }}-debian10_amd64.deb
    dest: /tmp/Nessus-{{ nessus_version }}-debian10_amd64.deb
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Install Nessus
  become: yes
  ansible.builtin.apt:
    deb: /tmp/Nessus-{{ nessus_version }}-debian10_amd64.deb
    state: present
    update_cache: yes
    force: yes

- name: Start Nessus
  become: yes
  ansible.builtin.service:
    name: nessusd
    state: stopped
    enabled: yes
