# Pip installation for tools
- name: Pip Install Tools - {{ item.name }}
  pip:
    chdir: "{{ vm_tools_dir }}/{{ item.name }}"
    virtualenv: "{{ vm_tools_dir }}/{{ item.name }}/venv"
    virtualenv_python: python3

    name: "{{ item.pip_packages | default(omit) }}"
    requirements: "{{ item.pip_requirements_file | default(omit) }}"
  when: item.pip is defined and item.pip
