- name: Install VSCode
  become: yes
  shell: |
    curl -L 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' --output /tmp/vscode.deb
    apt install /tmp/vscode.deb -y
  args:
    creates: "/usr/bin/code"
